### ISSUE TITLE
How to.

### ISSUE THREAD

**Issue by flovera1** [amplab/MLI#7]
Hi,
Is there any documentation of how to use this code? Let's say you have a csv file with features in string form and you wanna use this code with it.
How do you run it? Where is the I/O part? 

Best regards.

**Comment by etrain** [comment]
This project is no longer under active development. I recommend you check out MLlib (http://spark.apache.org/mllib/) or KeystoneML (http://keystone-ml.org/) for follow-on projects that share ideas but are still under active development.
